### ISSUE TITLE
Error in loading .dat file

### ISSUE THREAD

**Issue by jambudvipa** [muhanzhang/SEAL#1]
Running on USAir_1...	
/home/RAAVAN/torch/install/bin/luajit: cannot open <tempdata/USAir_1/USAir_1.dat> in mode r  at /tmp/luarocks_torch-scm-1-5020/torch7/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: at 0x7f0fb4144160
	[C]: in function 'DiskFile'
	/home/RAAVAN/.luarocks/share/lua/5.1/torch/File.lua:405: in function 'load'
	../DGCNN/main.lua:331: in function 'load_data'
	../DGCNN/main.lua:747: in main chunk
	[C]: in function 'dofile'
	...AVAN/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x004056e0

This error is coming from DCGNN

**Comment by muhanzhang** [comment]
Hi, thanks for raising the issue. Could you please try "th main.lua" within "DGCNN/" to see if it works properly by itself?

**Comment by jambudvipa** [comment]
Hi, thanks for quick reply. The problem were in the installation of matio, which has been resolved. 
But further I'm getting this error.

th ../DGCNN/main.lua -dataPos tempdata/USAir_2 -dataName USAir_2  -save tempdata -testNumber 424 -gpu 1 -maxEpoch 50 -k 0.4 -fixed_shuffle original -nodeLabel original -inputChannel 140
/home/raavan/torch/install/bin/luajit: /home/raavan/torch/install/share/lua/5.1/trepl/init.lua:389: /home/raavan/torch/install/share/lua/5.1/trepl/init.lua:389: /home/raavan/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/home/raavan/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
	[C]: in function 'error'
	/home/raavan/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	../DGCNN/main.lua:7: in main chunk
	[C]: in function 'dofile'
	...avan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405b70
Error using SEAL (line 112)
Unable to read file 'tempdata/USAir_2/finalAUC'. No such file or directory.


But when I run this (th ../DGCNN/main.lua -dataPos tempdata/USAir_2 -dataName USAir_2  -save tempdata -testNumber 424 -gpu 1 -maxEpoch 50 -k 0.4 -fixed_shuffle original -nodeLabel original -inputChannel 140) in separate terminal, it works fine. Also this generates the "finalAUC" file. But from matlab this commad is not working.

**Comment by muhanzhang** [comment]
Hi. This error is because MATLAB replaces system's default environment variables so that libcutorch.so is not found. Here is the solution (can also be found in my another repository LinkPrediction: https://github.com/muhanzhang/LinkPrediction).

If your MATLAB prints "cannot load ....../....../libcutorch.so", (that is because MATLAB replaces system's environment variables with its own ones when executing command 'system'.) please check your system's LD_LIBRARY_PATH by typing the following command in your shell:

echo $LD_LIBRARY_PATH

Then, in MATLAB, before running Main, type

setenv LD_LIBRARY_PATH what_you_got_from_the_echo_command

in order to recall system's LD_LIBRARY_PATH. After that, you should be able to run Torch scripts within MATLAB successfully.

**Comment by jambudvipa** [comment]
It worked. Thank You.
