### ISSUE TITLE
How are your predicted results stored and saved?

### ISSUE THREAD

**Issue by marioserao** [muhanzhang/SEAL#10]
Hi. great work. How can i have access to your predicted link results on those eight datasets? Any codes for that ? Currently, I got the auc and acc results stored in txt files.

Great work..

**Comment by muhanzhang** [comment]
Hi, thanks! If you need the predicted scores for test links, please uncomment this line in pytorch_DGCNN/main.py 
https://github.com/muhanzhang/pytorch_DGCNN/blob/1011318de78502a52e481c7d0c17ada8fbd1f001/main.py#L151

Then the scores will be saved in 'test_scores.txt' corresponding to the testing link indices provided in _links2subgraphs_, which can be used to construct the adjacency matrix or edgelist.

**Comment by marioserao** [comment]
Hi. Dr. Zhang,

I had re-run your default case (USair) and got the results for auc and acc, as well as the predicted scores for test links. I have some follow-up questions about the study. 

1) Could you possibly elaborate on the statistic meanings of the generated predicted scores? How were the predicting score used in predicting the existence of a link/links in the non-existence sample? 
2) Shouldn't the final predicted links output be the union set of E(observed) and E (predicted in the nonexistence dataset)? Apologize if I misunderstand your published paper. I thought the predicted data format is in binary as it indicates the (non-)existence of a predicted link.
3) In the case of US air lines, 332 nodes and 2,126 (undirected) links are observed. I assume there would be additional links predicted. if so, it is possible to generate or print the final output link edgelist/matrix in a binary form, or have I misundstand your paper.

Thank you very much for your response and patience. Much appreciation.

**Comment by muhanzhang** [comment]
1. I didn't make binary decisions out of the prediction scores, as AUC/AP calculation only requires scores. If you'd like to make binary decisions of link predictions, you may manually choose a threshold (or choose one via cross validation) to classify testing links with scores higher than the threshold as the predicted links.
2. Negative testing links are currently sampled from the set of E(nonexistence), thus only constitutes a portion of all potential links. But AUC/AP calculation is invariant to this sampling. If you want to make predictions for all links in E(nonexistence), you should modify your negative testing links to include all of them excluding those negative training links which are also sampled from E(nonexistence). We can't make predictions for these negative training links because we have already assumed their nonexistence. Although these negative training links are sampled randomly from E(nonexistence) in the implementation, in practice, they should better be those links that you are sure of their nonexistence.
3. It is possible, yet requiring additional work combining the answers in 1 and 2. I'll try to implement your request if I have time in the near future. Thanks.

**Comment by marioserao** [comment]
Thank you for your clarification. This surely helps me to understand your study better. 
Thank you for your patience.
