### ISSUE TITLE
Details about the train/test data

### ISSUE THREAD

**Issue by MengyangSun93** [muhanzhang/SEAL#18]
I saw that in your PB_train.txt and PB_test.txt, there are observed links for training, as well as "future" links for testing, right? 

Do they share the same node set? meaning, if test file contains a node id that doesn't appear in the train file, it it ok? or all the node ids should be specified in train file first? (I know that, if there is a future link both nodes of which didn't appear in train file, it would not be predictable since it is too far away from the community. But I just wonder for an engineering-concern about coding. :smile: )

Another question, for the testing file, do you mean that, if a link is in the test file, it is TRUE, otherwise it is FALSE, when you compute the ACC ? (Meaning the test file shouldn't contain only a subset of test links )

Thank you very much!! :smile_cat:

**Comment by muhanzhang** [comment]
Yes, PB_test.txt contains future positive links for testing. They share the same node set. Test set can contain node ids that don't appear in train, since the adjacency matrix size is determined by the maximum of all train indices and test indices. See line 78,79 in "util_functions.py". In SEAL, links are predicted based on their local structure patterns. Thus, even if a test link is far away from the train nodes community, it is still predictable as long as its local neighborhood can be sampled.

For the testing file, it should only contain those links that you are sure they exist (the true links in the future). The negative links will be sampled from the network.

**Comment by MengyangSun93** [comment]
> Yes, PB_test.txt contains future positive links for testing. They share the same node set. Test set can contain node ids that don't appear in train, since the adjacency matrix size is determined by the maximum of all train indices and test indices. See line 78,79 in "util_functions.py". In SEAL, links are predicted based on their local structure patterns. Thus, even if a test link is far away from the train nodes community, it is still predictable as long as its local neighborhood can be sampled.
> 
> For the testing file, it should only contain those links that you are sure they exist (the true links in the future). The negative links will be sampled from the network.

I got it!
Thank you very much.
