### ISSUE TITLE
Inquiry about scalability

### ISSUE THREAD

**Issue by kexinhuang12345** [muhanzhang/SEAL#19]
Hi Muhan,

Thank you for sharing this great code.

I am trying on large datasets like around 1800 nodes, 28000 links. However, the subgraph extraction process takes a lot of time (on USAir, it is pretty fast). Is this something anticipated? What is the complexity of this process? or if I am doing something wrong? Thank you!

![Screen Shot 2019-08-16 at 12 07 20 PM](https://user-images.githubusercontent.com/27795075/63181617-6d7d7080-c01e-11e9-9783-98f806817f00.png)

**Comment by muhanzhang** [comment]
Hi Kexin, thanks for the question. The subgraph extraction is naturally parallelizable. I just updated the code to make it parallel. On our 20-core server, the subgraph extraction process for PPI (3850 nodes, 76584 edges) takes about 3 minutes.

Please try the new version of code. If it is still too slow for you, two possible solutions are 1) reduce the hop number h to 1; and 2) reduce the number of training examples by adding "--max-train-num 10000" for example. SEAL usually does not need very large subgraphs or a large number of training data in order to achieve good performance.

**Comment by kexinhuang12345** [comment]
Thanks! I will try it out and send you some feedback
