### ISSUE TITLE
Determining the value of h

### ISSUE THREAD

**Issue by sbhttchryy** [muhanzhang/SEAL#21]
In util_functions. py the value of "h" gets selected between 1 and 2, on the basis of 
`if val_auc_AA >= val_auc_CN:
            h = 2
            print('\033[91mChoose h=2\033[0m')
        else:
            h = 1
            print('\033[91mChoose h=1\033[0m')`

From what I understood from the paper, the value of h can remain small because of the gamma decaying property. Which is why,
1. Is there a particular reason why you check if the val_auc_AA >= val_auc_CN to set the value of h ? 
2. Can I set the value of h arbitrarily between 1  and 2? Will it not give accurate results then?

Thank you.

**Comment by muhanzhang** [comment]
Hi, thanks for the questions. 1. It is because AA is a very popular second order heuristic, and CN is the most popular first-order heuristic. If AA is better than CN, it might suggest second-order information is useful in this network, thus suggesting an h=2.
2. No, h can only be an integer. You can set h to be 1,2,3... as long as your memory fits the data.
