### ISSUE TITLE
Inquiry about consumption of memory

### ISSUE THREAD

**Issue by williamweiwu** [muhanzhang/SEAL#44]
Dear Dr. Zhang,

I am running on 12-core server with 220G memory and 4 GPUs. The data has 2511 nodes, 37154 edges and 9073 attributes, and the average degree is 29.59.

In SEAL, max-train-num is set to 10000 and args.max_nodes_per_hop is set to 100.

The algorithm runs successfully when hop = 1. However, in the case of hop =2, it throws memory error due to memory exhaustion. 

Could you give me suggestions pls?

Thanks
Wei

**Comment by muhanzhang** [comment]
The memory consumption increases exponentially with hops. If hop=2 OOMs and you still want to use hop=2, you may keep decreasing max_nodes_per_hop to a smaller value, or further reduce the max-train-num.

**Comment by joc32** [comment]
May I ask you @muhanzhang , what were the parameters of your computer setup when you were running SEAL with hops = 2 on the big datasets like (Arxiv, FB, Wikipedia, Blogpost) so that I know how much RAM I approximately need?

Seems like the building of the SEALDataset from TorchGeometric is the most demanding task. Even to build the PB dataset, it took me around 800 seconds to be done with hops = 1. I am using SEAL code from PTG Link Prediction demo. 

Thanks,
Joe

**Comment by muhanzhang** [comment]
Pytorch Geometric default k-hop subgraph sampler is slow. I will release a new version (possibly merge to PyG) with much faster (~1000 times) speed up recently. Please stay tuned. I'll let you know when it is released.

**Comment by joc32** [comment]
@muhanzhang That would be much appreciated! Even if you could share it somehow as a gist in some beta version. I need it for my MSc thesis and so far I cannot run Arxiv and Facebook with SEAL as it is really slow.

**Comment by muhanzhang** [comment]
Hi @joc32 , the new version of SEAL is [here](https://github.com/facebookresearch/SEAL_OGB). It runs on OGB benchmark datasets.

**Comment by joc32** [comment]
Thanks very much @muhanzhang , will look into it.
