### ISSUE TITLE
About running time

### ISSUE THREAD

**Issue by wenyuema-cs** [muhanzhang/SEAL#47]
Hi muhan, 

Thanks for sharing the code, I've run it by both `python Main.py --data--name USAir --hop 'auto' --batch-size 1` and `python Main.py --data--name USAir --hop 1 --batch-size 1`, the sampling of subgraph run smoothly, but it seems to suck after print `Initializing DGCNN`.
The previous command has run over 2 days still without output file `auc_results.txt`. And now the second command has run over 4 hours without printing a log or file. 
I thought it was because the subgraph is very large due to 'auto -hop', but still suck after changing hop arg to 1 hop
does it correct, did u spend time on training and get auc results?

**Comment by muhanzhang** [comment]
![image](https://user-images.githubusercontent.com/19640852/100379300-80c10f00-2fc9-11eb-8512-1c6e67109a3d.png)

Hi, this is my log output after running `python Main.py --data-name USAir --hop 'auto' --batch-size 1` (--data-name instead of --data--name). Can you check your CPU usage or GPU usage while stucked to see whether it is training or not? Also, can you check whether your pytorch_DGCNN is successfully installed and compiled following its [instruction](https://github.com/muhanzhang/pytorch_DGCNN)?

**Comment by wenyuema-cs** [comment]
Thanks a lot, I've solved this issue by applying this code to another server.
Thought it was because the previous server's resource limit
