### ISSUE TITLE
关于模型预测值

### ISSUE THREAD

**Issue by amiduai** [muhanzhang/SEAL#66]
首先，我用以下命令训练得到了一个模型。
`python Main.py --train-name PB_train.txt --test-name PB_val.txt --hop 1 --save-model`

然后，我用--only-predict选项使用这个模型进行预测，我把--test-name分别设置成：
`PB_test.txt   PB_val.txt  PB_train.txt`。
比如：
`python Main.py --train-name PB_train.txt --test-name PB_val.txt --hop 1 --only-predict`

之后，生成了三个文件: `PB_test_pred.txt  PB_val_pred.txt  PB_train_pred.txt`。
其中，`PB_test_pred.txt`和`PB_val_pred.txt`看起来比较正常，大部分的预测值都大于0.5。

但是`PB_train_pred.txt`所有预测值都是0.03（如下图）。
这是为什么呢？不应该预测值都接近1吗？
![image](https://user-images.githubusercontent.com/37824442/142796269-b862008c-5e5f-40f2-b927-eabbf65330eb.png)

**Comment by muhanzhang** [comment]
Hi! It is because you used training links as testing links, and the testing links will be removed from the training graph before applying the model. See [here](https://github.com/muhanzhang/SEAL/blob/ca1f019a15fb0c21796042165b4e6bee73981dd3/Python/Main.py#L132). After removing all the training (testing) links, the training graph will be empty. You can check `A.nnz` to verify it.

**Comment by amiduai** [comment]
Yeah, A.nnz is 0.  
My inattentive.
Thank you !

**Comment by amiduai** [comment]
Yeah, A.nnz is 0.  
My inattentive.
Thank you !

**Comment by amiduai** [comment]
Yeah, A.nnz is 0.  
My inattentive.
Thank you !
