### ISSUE TITLE
Where should change if apply this method in directed graph?

### ISSUE THREAD

**Issue by XuSShuai** [muhanzhang/SEAL#7]
In the paper, the G assume to be undirected graph, if i want to apply the SEAL on directed network, where are the different points? 
Thank you!

**Comment by muhanzhang** [comment]
Hi there, SEAL doesn't support directed network yet since the GNN it is based on works for undirected graphs only. One possible extension is to modify the GNN so that edges propagate information only along their directions. I'll add this function if I have time in the future. Currently, you may also try to treat directed edges as undirected edges all the same. The results should be good too.

**Comment by XuSShuai** [comment]
Thanks for your reply so much.
